
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
      export type L1Operation = {
        
      }
    

/**
 * Type-safe interface for contract Broadcaster;
 */
export class BroadcasterContract extends ContractBase {
  
  private constructor(address: AztecAddress, artifact: ContractArtifact, wallet: Wallet) {
    super(address, artifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(address: AztecAddress, artifact: ContractArtifact, wallet: Wallet): BroadcasterContract {
    return Contract.at(address, artifact, wallet) as BroadcasterContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, artifact: ContractArtifact, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<BroadcasterContract>(
      wallet,
      {
        artifact,
        postDeployCtor: (instance, wallet) => BroadcasterContract.at(instance.address, artifact, wallet),
        args: [],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof BroadcasterContract["methods"]>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions; artifact: ContractArtifact },
    ...args: Parameters<BroadcasterContract["methods"][M]>
  ) {
    return DeployMethod.create<BroadcasterContract>(
      opts.wallet,
      {
        artifact: opts.artifact,
        postDeployCtor: (instance, wallet) => BroadcasterContract.at(instance.address, opts.artifact, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? "constructor",
      },
      opts.instantiation,
    );
  }
  

  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** broadcast_l1_operation_128k(target: struct, payout_token: struct, l1_calldata_bytes_len: integer, l1_calldata: array, condition: struct) */
    broadcast_l1_operation_128k: ((target: EthAddressLike, payout_token: EthAddressLike, l1_calldata_bytes_len: (bigint | number), l1_calldata: FieldLike[], condition: { kind: (bigint | number), token: EthAddressLike, recipient: EthAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** broadcast_l1_operation_16k(target: struct, payout_token: struct, l1_calldata_bytes_len: integer, l1_calldata: array, condition: struct) */
    broadcast_l1_operation_16k: ((target: EthAddressLike, payout_token: EthAddressLike, l1_calldata_bytes_len: (bigint | number), l1_calldata: FieldLike[], condition: { kind: (bigint | number), token: EthAddressLike, recipient: EthAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** broadcast_l1_operation_2k(target: struct, payout_token: struct, l1_calldata_bytes_len: integer, l1_calldata: array, condition: struct) */
    broadcast_l1_operation_2k: ((target: EthAddressLike, payout_token: EthAddressLike, l1_calldata_bytes_len: (bigint | number), l1_calldata: FieldLike[], condition: { kind: (bigint | number), token: EthAddressLike, recipient: EthAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** broadcast_l1_operation_32k(target: struct, payout_token: struct, l1_calldata_bytes_len: integer, l1_calldata: array, condition: struct) */
    broadcast_l1_operation_32k: ((target: EthAddressLike, payout_token: EthAddressLike, l1_calldata_bytes_len: (bigint | number), l1_calldata: FieldLike[], condition: { kind: (bigint | number), token: EthAddressLike, recipient: EthAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** broadcast_l1_operation_4k(target: struct, payout_token: struct, l1_calldata_bytes_len: integer, l1_calldata: array, condition: struct) */
    broadcast_l1_operation_4k: ((target: EthAddressLike, payout_token: EthAddressLike, l1_calldata_bytes_len: (bigint | number), l1_calldata: FieldLike[], condition: { kind: (bigint | number), token: EthAddressLike, recipient: EthAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** broadcast_l1_operation_64k(target: struct, payout_token: struct, l1_calldata_bytes_len: integer, l1_calldata: array, condition: struct) */
    broadcast_l1_operation_64k: ((target: EthAddressLike, payout_token: EthAddressLike, l1_calldata_bytes_len: (bigint | number), l1_calldata: FieldLike[], condition: { kind: (bigint | number), token: EthAddressLike, recipient: EthAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** broadcast_l1_operation_pair_2k(targets: array, payout_tokens: array, l1_calldata_bytes_lens: array, l1_calldatas: array, conditions: array) */
    broadcast_l1_operation_pair_2k: ((targets: EthAddressLike[], payout_tokens: EthAddressLike[], l1_calldata_bytes_lens: (bigint | number)[], l1_calldatas: FieldLike[][], conditions: { kind: (bigint | number), token: EthAddressLike, recipient: EthAddressLike }[]) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** l1_operation_event() */
    l1_operation_event: (() => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;
  };

  
    public static get events(): { L1Operation: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      L1Operation: {
        abiType: {
    "kind": "struct",
    "fields": [],
    "path": "Broadcaster::L1Operation"
},
        eventSelector: EventSelector.fromString("0x103c3e90"),
        fieldNames: [],
      }
    };
  }
  
}
