
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
/**
 * Type-safe interface for contract ClaimFPC;
 */
export class ClaimFPCContract extends ContractBase {
  
  private constructor(address: AztecAddress, artifact: ContractArtifact, wallet: Wallet) {
    super(address, artifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(address: AztecAddress, artifact: ContractArtifact, wallet: Wallet): ClaimFPCContract {
    return Contract.at(address, artifact, wallet) as ClaimFPCContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, artifact: ContractArtifact, password_hash: FieldLike, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<ClaimFPCContract>(
      wallet,
      {
        artifact,
        postDeployCtor: (instance, wallet) => ClaimFPCContract.at(instance.address, artifact, wallet),
        args: [password_hash],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof ClaimFPCContract["methods"]>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions; artifact: ContractArtifact },
    ...args: Parameters<ClaimFPCContract["methods"][M]>
  ) {
    return DeployMethod.create<ClaimFPCContract>(
      opts.wallet,
      {
        artifact: opts.artifact,
        postDeployCtor: (instance, wallet) => ClaimFPCContract.at(instance.address, opts.artifact, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? "constructor",
      },
      opts.instantiation,
    );
  }
  

  public static get storage(): ContractStorageLayout<'password_hash' | 'config' | 'subscriptions'> {
      return {
        password_hash: {
      slot: new Fr(1n),
    },
config: {
      slot: new Fr(3n),
    },
subscriptions: {
      slot: new Fr(32n),
    }
      } as ContractStorageLayout<'password_hash' | 'config' | 'subscriptions'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** configure(password: string, config: struct) */
    configure: ((password: string, config: { domain_owner_pub_key_x_hi: FieldLike, domain_owner_pub_key_x_lo: FieldLike, domain_owner_pub_key_y_hi: FieldLike, domain_owner_pub_key_y_lo: FieldLike, registry_domain_separator_hi: FieldLike, registry_domain_separator_lo: FieldLike, factory_address: FieldLike, implementation_address: FieldLike, name_portal_address: FieldLike, max_fee_per_da_gas: (bigint | number), max_fee_per_l2_gas: (bigint | number), rails: { gate_selector: FieldLike, policy_root: FieldLike, max_tx: (bigint | number), refill_period: (bigint | number) }[], claim_secret: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** constructor(password_hash: field) */
    constructor: ((password_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** get_config() */
    get_config: (() => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** get_subscription_uses(user: struct, rail_id: integer) */
    get_subscription_uses: ((user: AztecAddressLike, rail_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** has_subscription(user: struct, rail_id: integer) */
    has_subscription: ((user: AztecAddressLike, rail_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** is_configured() */
    is_configured: (() => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** refuel(amount: integer, message_leaf_index: field) */
    refuel: ((amount: (bigint | number), message_leaf_index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** sponsor(rail_id: integer, calls: array, class_witnesses: array, policy_witnesses: array, public_calldata: array, public_calldata_lens: array, user: struct) */
    sponsor: ((rail_id: (bigint | number), calls: { args_hash: FieldLike, function_selector: FunctionSelectorLike, target_address: AztecAddressLike, is_public: boolean, hide_msg_sender: boolean, is_static: boolean }[], class_witnesses: { class_id: FieldLike, salted_initialization_hash: FieldLike, public_keys: PublicKeys }[], policy_witnesses: { entry: { kind: (bigint | number), target: FieldLike, selector: FieldLike, max_fee: (bigint | number) }, leaf_index: (bigint | number), sibling_path: FieldLike[] }[], public_calldata: FieldLike[][], public_calldata_lens: (bigint | number)[], user: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** subscribe(rail_id: integer, calls: array, class_witnesses: array, policy_witnesses: array, public_calldata: array, public_calldata_lens: array, user: struct, gate_args_hash: field) */
    subscribe: ((rail_id: (bigint | number), calls: { args_hash: FieldLike, function_selector: FunctionSelectorLike, target_address: AztecAddressLike, is_public: boolean, hide_msg_sender: boolean, is_static: boolean }[], class_witnesses: { class_id: FieldLike, salted_initialization_hash: FieldLike, public_keys: PublicKeys }[], policy_witnesses: { entry: { kind: (bigint | number), target: FieldLike, selector: FieldLike, max_fee: (bigint | number) }, leaf_index: (bigint | number), sibling_path: FieldLike[] }[], public_calldata: FieldLike[][], public_calldata_lens: (bigint | number)[], user: AztecAddressLike, gate_args_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;
  };

  
}
