
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
/**
 * Type-safe interface for contract OidcKeyRegistry;
 */
export class OidcKeyRegistryContract extends ContractBase {
  
  private constructor(address: AztecAddress, artifact: ContractArtifact, wallet: Wallet) {
    super(address, artifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(address: AztecAddress, artifact: ContractArtifact, wallet: Wallet): OidcKeyRegistryContract {
    return Contract.at(address, artifact, wallet) as OidcKeyRegistryContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, artifact: ContractArtifact, operator: AztecAddressLike, guardian: AztecAddressLike, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<OidcKeyRegistryContract>(
      wallet,
      {
        artifact,
        postDeployCtor: (instance, wallet) => OidcKeyRegistryContract.at(instance.address, artifact, wallet),
        args: [operator, guardian],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof OidcKeyRegistryContract["methods"]>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions; artifact: ContractArtifact },
    ...args: Parameters<OidcKeyRegistryContract["methods"][M]>
  ) {
    return DeployMethod.create<OidcKeyRegistryContract>(
      opts.wallet,
      {
        artifact: opts.artifact,
        postDeployCtor: (instance, wallet) => OidcKeyRegistryContract.at(instance.address, opts.artifact, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? "constructor",
      },
      opts.instantiation,
    );
  }
  

  public static get storage(): ContractStorageLayout<'operator' | 'guardian' | 'paused' | 'update_index' | 'jwks_allowlist' | 'aud_allowlist'> {
      return {
        operator: {
      slot: new Fr(1n),
    },
guardian: {
      slot: new Fr(2n),
    },
paused: {
      slot: new Fr(3n),
    },
update_index: {
      slot: new Fr(4n),
    },
jwks_allowlist: {
      slot: new Fr(5n),
    },
aud_allowlist: {
      slot: new Fr(6n),
    }
      } as ContractStorageLayout<'operator' | 'guardian' | 'paused' | 'update_index' | 'jwks_allowlist' | 'aud_allowlist'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_aud(aud: field) */
    add_aud: ((aud: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** assert_valid(h_iss: field, aud: field, pubkey_hash: field, iat: integer) */
    assert_valid: ((h_iss: FieldLike, aud: FieldLike, pubkey_hash: FieldLike, iat: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** constructor(operator: struct, guardian: struct) */
    constructor: ((operator: AztecAddressLike, guardian: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** invalidate_issuer(h_iss: field) */
    invalidate_issuer: ((h_iss: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** is_aud_allowed(aud: field) */
    is_aud_allowed: ((aud: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** is_valid_jwk(h_iss: field, pubkey_hash: field) */
    is_valid_jwk: ((h_iss: FieldLike, pubkey_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** remove_aud(aud: field) */
    remove_aud: ((aud: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** rotate_operator(new_operator: struct) */
    rotate_operator: ((new_operator: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** set_issuer_jwks(h_iss: field, pubkey_hashes: array, count: integer) */
    set_issuer_jwks: ((h_iss: FieldLike, pubkey_hashes: FieldLike[], count: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** set_paused(paused: boolean) */
    set_paused: ((paused: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;
  };

  
}
