
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
      export type Withdraw = {
        from: AztecAddressLike
executor: EthAddressLike
amount: (bigint | number)
meta: FieldLike[]
      }
    

      export type Transfer = {
        from: AztecAddressLike
to: AztecAddressLike
amount: (bigint | number)
meta: FieldLike[]
      }
    

      export type SIPA = {
        shared_secret_salt: FieldLike
resweepable: boolean
intent_hash_hi: (bigint | number)
intent_hash_lo: (bigint | number)
      }
    

/**
 * Type-safe interface for contract OxideToken;
 */
export class OxideTokenContract extends ContractBase {
  
  private constructor(address: AztecAddress, artifact: ContractArtifact, wallet: Wallet) {
    super(address, artifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(address: AztecAddress, artifact: ContractArtifact, wallet: Wallet): OxideTokenContract {
    return Contract.at(address, artifact, wallet) as OxideTokenContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, artifact: ContractArtifact, portal_address: EthAddressLike, name: string, symbol: string, decimals: (bigint | number), instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<OxideTokenContract>(
      wallet,
      {
        artifact,
        postDeployCtor: (instance, wallet) => OxideTokenContract.at(instance.address, artifact, wallet),
        args: [portal_address, name, symbol, decimals],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof OxideTokenContract["methods"]>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions; artifact: ContractArtifact },
    ...args: Parameters<OxideTokenContract["methods"][M]>
  ) {
    return DeployMethod.create<OxideTokenContract>(
      opts.wallet,
      {
        artifact: opts.artifact,
        postDeployCtor: (instance, wallet) => OxideTokenContract.at(instance.address, opts.artifact, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? "constructor",
      },
      opts.instantiation,
    );
  }
  

  public static get storage(): ContractStorageLayout<'portal_address' | 'balances' | 'approved_signers' | 'name' | 'symbol' | 'decimals'> {
      return {
        portal_address: {
      slot: new Fr(1n),
    },
balances: {
      slot: new Fr(3n),
    },
approved_signers: {
      slot: new Fr(4n),
    },
name: {
      slot: new Fr(5n),
    },
symbol: {
      slot: new Fr(7n),
    },
decimals: {
      slot: new Fr(9n),
    }
      } as ContractStorageLayout<'portal_address' | 'balances' | 'approved_signers' | 'name' | 'symbol' | 'decimals'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** balance_of(owner: struct) */
    balance_of: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** constructor(portal_address: struct, name: string, symbol: string, decimals: integer) */
    constructor: ((portal_address: EthAddressLike, name: string, symbol: string, decimals: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** consume_signer_registration(pub_key_x_hi: field, pub_key_x_lo: field, pub_key_y_hi: field, pub_key_y_lo: field, message_leaf_index: field) */
    consume_signer_registration: ((pub_key_x_hi: FieldLike, pub_key_x_lo: FieldLike, pub_key_y_hi: FieldLike, pub_key_y_lo: FieldLike, message_leaf_index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** decimals() */
    decimals: (() => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** enumerate_owned_notes(owner: struct, offset: integer) */
    enumerate_owned_notes: ((owner: AztecAddressLike, offset: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** name() */
    name: (() => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** notify_sipa_recipient(recipient: struct, shared_secret_salt: field, resweepable: boolean, intent_hash_hi: integer, intent_hash_lo: integer) */
    notify_sipa_recipient: ((recipient: AztecAddressLike, shared_secret_salt: FieldLike, resweepable: boolean, intent_hash_hi: (bigint | number), intent_hash_lo: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** publish_da() */
    publish_da: (() => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** store_deposit(inbox_index: field, amount: integer, recipient: struct, shared_secret_salt: field) */
    store_deposit: ((inbox_index: FieldLike, amount: (bigint | number), recipient: AztecAddressLike, shared_secret_salt: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** symbol() */
    symbol: (() => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** transfer(from: struct, to: struct, amount: integer, meta: array, authwit_nonce: field) */
    transfer: ((from: AztecAddressLike, to: AztecAddressLike, amount: (bigint | number), meta: FieldLike[], authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** withdraw(from: struct, executor: struct, user_payload_hash: field, amount: integer, prover_tip: integer, meta: array, authwit_nonce: field) */
    withdraw: ((from: AztecAddressLike, executor: EthAddressLike, user_payload_hash: FieldLike, amount: (bigint | number), prover_tip: (bigint | number), meta: FieldLike[], authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;
  };

  
    public static get events(): { Withdraw: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, Transfer: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, SIPA: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      Withdraw: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "from",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "executor",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::eth_address::EthAddress"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 128
            }
        },
        {
            "name": "meta",
            "type": {
                "kind": "array",
                "length": 7,
                "type": {
                    "kind": "field"
                }
            }
        }
    ],
    "path": "OxideToken::Withdraw"
},
        eventSelector: EventSelector.fromString("0x5d28e2c5"),
        fieldNames: ["from","executor","amount","meta"],
      },
Transfer: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "from",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "to",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 128
            }
        },
        {
            "name": "meta",
            "type": {
                "kind": "array",
                "length": 7,
                "type": {
                    "kind": "field"
                }
            }
        }
    ],
    "path": "OxideToken::Transfer"
},
        eventSelector: EventSelector.fromString("0x19d534bf"),
        fieldNames: ["from","to","amount","meta"],
      },
SIPA: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "shared_secret_salt",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "resweepable",
            "type": {
                "kind": "boolean"
            }
        },
        {
            "name": "intent_hash_hi",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 128
            }
        },
        {
            "name": "intent_hash_lo",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 128
            }
        }
    ],
    "path": "OxideToken::SIPA"
},
        eventSelector: EventSelector.fromString("0xa836fcaf"),
        fieldNames: ["shared_secret_salt","resweepable","intent_hash_hi","intent_hash_lo"],
      }
    };
  }
  
}
