
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
/**
 * Type-safe interface for contract PasswordFPC;
 */
export class PasswordFPCContract extends ContractBase {
  
  private constructor(address: AztecAddress, artifact: ContractArtifact, wallet: Wallet) {
    super(address, artifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(address: AztecAddress, artifact: ContractArtifact, wallet: Wallet): PasswordFPCContract {
    return Contract.at(address, artifact, wallet) as PasswordFPCContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, artifact: ContractArtifact, password: string, max_fee: (bigint | number), instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<PasswordFPCContract>(
      wallet,
      {
        artifact,
        postDeployCtor: (instance, wallet) => PasswordFPCContract.at(instance.address, artifact, wallet),
        args: [password, max_fee],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PasswordFPCContract["methods"]>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions; artifact: ContractArtifact },
    ...args: Parameters<PasswordFPCContract["methods"][M]>
  ) {
    return DeployMethod.create<PasswordFPCContract>(
      opts.wallet,
      {
        artifact: opts.artifact,
        postDeployCtor: (instance, wallet) => PasswordFPCContract.at(instance.address, opts.artifact, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? "constructor",
      },
      opts.instantiation,
    );
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'password' | 'max_fee'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
password: {
      slot: new Fr(3n),
    },
max_fee: {
      slot: new Fr(5n),
    }
      } as ContractStorageLayout<'admin' | 'password' | 'max_fee'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(password: string, max_fee: integer) */
    constructor: ((password: string, max_fee: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** constructor_and_pay(admin: struct, password_hash: field, max_fee: integer) */
    constructor_and_pay: ((admin: AztecAddressLike, password_hash: FieldLike, max_fee: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** fee_entrypoint_private(max_fee: integer, nonce: field, password: string) */
    fee_entrypoint_private: ((max_fee: (bigint | number), nonce: FieldLike, password: string) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** get_accepted_asset() */
    get_accepted_asset: (() => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** refuel(amount: integer, claim_secret: field, message_leaf_index: field) */
    refuel: ((amount: (bigint | number), claim_secret: FieldLike, message_leaf_index: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;
  };

  
}
