
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
/**
 * Type-safe interface for contract PaylinkDirect;
 */
export class PaylinkDirectContract extends ContractBase {
  
  private constructor(address: AztecAddress, artifact: ContractArtifact, wallet: Wallet) {
    super(address, artifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(address: AztecAddress, artifact: ContractArtifact, wallet: Wallet): PaylinkDirectContract {
    return Contract.at(address, artifact, wallet) as PaylinkDirectContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, artifact: ContractArtifact, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<PaylinkDirectContract>(
      wallet,
      {
        artifact,
        postDeployCtor: (instance, wallet) => PaylinkDirectContract.at(instance.address, artifact, wallet),
        args: [],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PaylinkDirectContract["methods"]>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions; artifact: ContractArtifact },
    ...args: Parameters<PaylinkDirectContract["methods"][M]>
  ) {
    return DeployMethod.create<PaylinkDirectContract>(
      opts.wallet,
      {
        artifact: opts.artifact,
        postDeployCtor: (instance, wallet) => PaylinkDirectContract.at(instance.address, opts.artifact, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? "constructor",
      },
      opts.instantiation,
    );
  }
  

  public static get storage(): ContractStorageLayout<'paylink_direct_note'> {
      return {
        paylink_direct_note: {
      slot: new Fr(1n),
    }
      } as ContractStorageLayout<'paylink_direct_note'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** claim(recipient: struct, authwit_nonce: field, meta: array) */
    claim: ((recipient: AztecAddressLike, authwit_nonce: FieldLike, meta: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** claim_to_l1(executor: struct, user_payload_hash: field, prover_tip: integer) */
    claim_to_l1: ((executor: EthAddressLike, user_payload_hash: FieldLike, prover_tip: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** deposit(amount: integer, from_claimable: integer, until_claimable: integer, refundable_until: integer, token_address: struct, sender: struct, meta: array) */
    deposit: ((amount: (bigint | number), from_claimable: (bigint | number), until_claimable: (bigint | number), refundable_until: (bigint | number), token_address: AztecAddressLike, sender: AztecAddressLike, meta: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** refund(sender: struct, authwit_nonce: field, meta: array) */
    refund: ((sender: AztecAddressLike, authwit_nonce: FieldLike, meta: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** sync_note() */
    sync_note: (() => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;
  };

  
}
