
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
      export type Transfer = {
        from: AztecAddressLike
to: AztecAddressLike
amount: (bigint | number)
meta: FieldLike[]
      }
    

/**
 * Type-safe interface for contract TestToken;
 */
export class TestTokenContract extends ContractBase {
  
  private constructor(address: AztecAddress, artifact: ContractArtifact, wallet: Wallet) {
    super(address, artifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(address: AztecAddress, artifact: ContractArtifact, wallet: Wallet): TestTokenContract {
    return Contract.at(address, artifact, wallet) as TestTokenContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, artifact: ContractArtifact, name: string, symbol: string, decimals: (bigint | number), minter: AztecAddressLike, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<TestTokenContract>(
      wallet,
      {
        artifact,
        postDeployCtor: (instance, wallet) => TestTokenContract.at(instance.address, artifact, wallet),
        args: [name, symbol, decimals, minter],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof TestTokenContract["methods"]>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions; artifact: ContractArtifact },
    ...args: Parameters<TestTokenContract["methods"][M]>
  ) {
    return DeployMethod.create<TestTokenContract>(
      opts.wallet,
      {
        artifact: opts.artifact,
        postDeployCtor: (instance, wallet) => TestTokenContract.at(instance.address, opts.artifact, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? "constructor",
      },
      opts.instantiation,
    );
  }
  

  public static get storage(): ContractStorageLayout<'name' | 'symbol' | 'decimals' | 'private_balances' | 'minter'> {
      return {
        name: {
      slot: new Fr(1n),
    },
symbol: {
      slot: new Fr(3n),
    },
decimals: {
      slot: new Fr(5n),
    },
private_balances: {
      slot: new Fr(7n),
    },
minter: {
      slot: new Fr(8n),
    }
      } as ContractStorageLayout<'name' | 'symbol' | 'decimals' | 'private_balances' | 'minter'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** balance_of(owner: struct) */
    balance_of: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** constructor(name: string, symbol: string, decimals: integer, minter: struct) */
    constructor: ((name: string, symbol: string, decimals: (bigint | number), minter: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** decimals() */
    decimals: (() => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** mint_to_private(to: struct, amount: integer) */
    mint_to_private: ((to: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** name() */
    name: (() => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** noop() */
    noop: (() => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** symbol() */
    symbol: (() => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;

    /** transfer(from: struct, to: struct, amount: integer, meta: array, authwit_nonce: field) */
    transfer: ((from: AztecAddressLike, to: AztecAddressLike, amount: (bigint | number), meta: FieldLike[], authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, "selector">;
  };

  
    public static get events(): { Transfer: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      Transfer: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "from",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "to",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 128
            }
        },
        {
            "name": "meta",
            "type": {
                "kind": "array",
                "length": 7,
                "type": {
                    "kind": "field"
                }
            }
        }
    ],
    "path": "TestToken::Transfer"
},
        eventSelector: EventSelector.fromString("0x19d534bf"),
        fieldNames: ["from","to","amount","meta"],
      }
    };
  }
  
}
