[package]
name = "obsidion_alpha_account"
type = "contract"
authors = ["porco"]
compiler_version = ">=0.35.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v5.2.0", directory = "noir-projects/aztec-nr/aztec" }
sha256 = { tag = "v0.2.1", git = "https://github.com/noir-lang/sha256" }
base64 = { tag = "v0.5.0", git = "https://github.com/noir-lang/noir_base64" }
alpha_lib = { path = "../lib" }
