// GENERATED by the ClaimFPC gas recorder — do not hand-edit.
// Regenerate: `pnpm gas:record` in packages/sdk against a fresh sandbox (two passes: the rows the
// per-call budgets derive from first, then every fpc suite).
// Each entry is the measured gas of a WHOLE sponsored tx (totalGas + teardownGas + any staged
// finalize delta), keyed by the batch shape it carried. Only shapes the shipped deployment can send
// belong here. It is the ground truth both policy shapes answer to: per-call budgets are read off
// it and checked against it (claimFpcGasBudgets.ts), and the flat CLAIM_FPC_MAX_BATCH_* caps the
// shipped open policy prices must cover every shape here (claimFpcGasInventory.test.ts).

/** Gas of one measured sponsored tx. */
export interface ClaimFpcMeasuredTx {
  daGas: number
  l2Gas: number
}

// prettier-ignore
export const CLAIM_FPC_GAS_TABLE: Record<string, ClaimFpcMeasuredTx> = /* TABLE_START */ {
  "refuel": {
    daGas: 224,
    l2Gas: 659123,
  },
  "sponsor[authorize_intents,oxide_token.transfer,oxide_token.publish_da]": {
    daGas: 4192,
    l2Gas: 595300,
  },
  "sponsor[authorize_intents,oxide_token.withdraw,broadcaster.broadcast_l1_operation_2k,oxide_token.publish_da]": {
    daGas: 3616,
    l2Gas: 831801,
  },
  "sponsor[authorize_intents,oxide_token.withdraw,broadcaster.broadcast_l1_operation_pair_2k,oxide_token.publish_da]": {
    daGas: 3712,
    l2Gas: 853238,
  },
  "sponsor[authorize_intents,paylink_direct.claim,oxide_token.publish_da]": {
    daGas: 3616,
    l2Gas: 599600,
  },
  "sponsor[authorize_intents,paylink_direct.claim,oxide_token.withdraw,broadcaster.broadcast_l1_operation_2k,oxide_token.publish_da]": {
    daGas: 4800,
    l2Gas: 929201,
  },
  "sponsor[authorize_intents,paylink_direct.deposit,claim_fpc.gift_voucher,oxide_token.publish_da]": {
    daGas: 7200,
    l2Gas: 724600,
  },
  "sponsor[authorize_intents,paylink_direct.deposit,oxide_token.publish_da]": {
    daGas: 6016,
    l2Gas: 685200,
  },
  "sponsor[authorize_intents,paylink_email.claim_to_l1,broadcaster.broadcast_l1_operation_2k,oxide_token.publish_da]": {
    daGas: 2944,
    l2Gas: 842511,
  },
  "sponsor[authorize_intents,paylink_email.claim,oxide_token.publish_da]": {
    daGas: 3552,
    l2Gas: 868410,
  },
  "sponsor[authorize_intents,paylink_email.deposit,claim_fpc.gift_voucher,oxide_token.publish_da]": {
    daGas: 7200,
    l2Gas: 724600,
  },
  "sponsor[authorize_intents,paylink_email.deposit,oxide_token.publish_da]": {
    daGas: 6016,
    l2Gas: 685200,
  },
  "sponsor[authorize_intents,test_token.transfer]": {
    daGas: 3264,
    l2Gas: 617300,
  },
  "sponsor[authorize_intents]": {
    daGas: 1408,
    l2Gas: 511400,
  },
  "sponsor[broadcaster.broadcast_l1_operation_2k]": {
    daGas: 832,
    l2Gas: 644812,
  },
  "sponsor[broadcaster.broadcast_l1_operation_4k]": {
    daGas: 832,
    l2Gas: 644812,
  },
  "sponsor[broadcaster.broadcast_l1_operation_pair_2k]": {
    daGas: 928,
    l2Gas: 666249,
  },
  "sponsor[claim_fpc.gift_voucher]": {
    daGas: 1984,
    l2Gas: 523100,
  },
  "sponsor[oxide_token.notify_sipa_recipient,broadcaster.broadcast_l1_operation_2k]": {
    daGas: 1408,
    l2Gas: 678112,
  },
  "sponsor[paylink_direct.claim_to_l1,broadcaster.broadcast_l1_operation_2k,oxide_token.publish_da]": {
    daGas: 2336,
    l2Gas: 754951,
  },
  "sponsor[paylink_email.claim_to_l1,broadcaster.broadcast_l1_operation_2k,oxide_token.publish_da]": {
    daGas: 2336,
    l2Gas: 789936,
  },
  "subscribe[nameClaim,oxide_token.notify_sipa_recipient,broadcaster.broadcast_l1_operation_2k]": {
    daGas: 1408,
    l2Gas: 678112,
  },
  "subscribe[registration,authorize_intents,test_token.transfer]": {
    daGas: 5600,
    l2Gas: 693700,
  },
  "subscribe[registration,authorize_intents]": {
    daGas: 1440,
    l2Gas: 527400,
  },
  "subscribe[registration,oxide_token.notify_sipa_recipient,broadcaster.broadcast_l1_operation_2k]": {
    daGas: 1440,
    l2Gas: 708912,
  },
} /* TABLE_END */
