/**
 * The pinned verification key for the zkJWT circuit — the `[Field; 115]` PaylinkEmail.claim takes.
 *
 * Every deposit binds `ZKJWT_VKEY_HASH` into the escrow note and the claim's recursive verify
 * checks the supplied vkey against it, so the fields a claimer sends must hash to the pin —
 * asserted here so a stale constant fails at claim-build time with a clear error instead of an
 * on-chain vkey-hash mismatch. Shipping the key rather than deriving it spares clients bb.js's
 * `getVerificationKey`, which costs as much as proving. Regenerated by `refreshZkJwtVkeyHash`
 * (packages/contracts/scripts/paylinkCodegen.ts) from the same bb output as the hash.
 */

import { Buffer } from "buffer"
import { poseidon2Hash } from "@aztec/foundation/crypto/poseidon"
import { Fr } from "@aztec/foundation/curves/bn254"
import { VKEY_FIELD_COUNT, ZKJWT_VKEY_HASH, ZKJWT_VK_BASE64 } from "@obsidion/core/constants"

let cachedVkey: Promise<Fr[]> | null = null

/** The zkJWT vkey fields, hash-checked against `ZKJWT_VKEY_HASH` on first use. */
export function getZkJwtVkey(): Promise<Fr[]> {
  cachedVkey ??= (async () => {
    const bytes = Buffer.from(ZKJWT_VK_BASE64, "base64")
    if (bytes.length !== VKEY_FIELD_COUNT * 32) {
      throw new Error(
        `zkJWT vkey is ${bytes.length} bytes, expected ${VKEY_FIELD_COUNT * 32} — ` +
          "rerun refreshZkJwtVkeyHash",
      )
    }
    const fields = Array.from({ length: VKEY_FIELD_COUNT }, (_, i) =>
      Fr.fromBuffer(Buffer.from(bytes.subarray(i * 32, (i + 1) * 32))),
    )
    const hash = (await poseidon2Hash(fields)).toString()
    if (hash !== ZKJWT_VKEY_HASH) {
      throw new Error(
        `pinned zkJWT vkey hashes to ${hash} but ZKJWT_VKEY_HASH = ${ZKJWT_VKEY_HASH} — ` +
          "the two constants drifted; rerun refreshZkJwtVkeyHash",
      )
    }
    return fields
  })()
  return cachedVkey
}
